Repository NAMSAN-MT/Namsan, pull requests merged in 2023-02, with the labels that each got.

#4 [fix]: gatsby 전역에 globalStyle, provider 래핑
  gatsby-browser.tsx
  gatsby-ssr.tsx
  src/components/common/Layout/index.tsx
Labels: fix

#3 몇가지 부가기능 추가
  .eslintignore
  .eslintrc
  .github/PULL_REQUEST_TEMPLATE/ pull_request_template.md
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  yarn.lock
Labels: style, chore

#6 [feat]: 아이콘 추가
  gatsby-browser.tsx
  gatsby-ssr.tsx
  package.json
  src/assets/imgs/ic_+_hover.svg
  src/assets/imgs/ic_+_nor.svg
  src/assets/imgs/ic_-_hover.svg
  src/assets/imgs/ic_-_nor.svg
  src/assets/imgs/ic_arrow_down_th10.svg
  src/assets/imgs/ic_arrow_down_th15.svg
  src/assets/imgs/ic_arrow_drop_down.svg
  src/assets/imgs/ic_arrow_drop_left.svg
  src/assets/imgs/ic_arrow_drop_right.svg
  src/assets/imgs/ic_arrow_drop_up.svg
  src/assets/imgs/ic_arrow_left_th10.svg
  src/assets/imgs/ic_arrow_left_th15.svg
  src/assets/imgs/ic_arrow_left_th5.svg
  src/assets/imgs/ic_arrow_right_th10.svg
  src/assets/imgs/ic_arrow_right_th15.svg
  src/assets/imgs/ic_arrow_right_th5.svg
  src/assets/imgs/ic_arrow_up_th10.svg
  src/assets/imgs/ic_arrow_up_th15.svg
  src/assets/imgs/ic_home.svg
  src/assets/imgs/ic_menu_nor.svg
  src/assets/imgs/ic_open.svg
  src/components/icons/AddIcon/AddIcon.tsx
  src/components/icons/AddIcon/index.ts
  src/components/icons/FilledArrowIcon/FilledArrowIcon.tsx
  src/components/icons/FilledArrowIcon/index.ts
  src/components/icons/HomeIcon/HomeIcon.tsx
  src/components/icons/HomeIcon/index.ts
  src/components/icons/IconWrapper/IconWrapper.style.tsx
  src/components/icons/IconWrapper/IconWrapper.tsx
  src/components/icons/IconWrapper/index.ts
  src/components/icons/LineArrowIcon/LineArrowIcon.tsx
  src/components/icons/LineArrowIcon/index.ts
  src/components/icons/MenuIcon/MenuIcon.tsx
  src/components/icons/MenuIcon/index.ts
  src/components/icons/RemoveIcon/RemoveIcon.tsx
  src/components/icons/RemoveIcon/index.ts
  src/index.d.ts
  src/styled-components.d.ts
  src/styles/GlobalStyles.ts
  src/styles/mixin.style.ts
  src/styles/varialbes.style.ts
  yarn.lock
Labels: feat
