Repository NAMSAN-MT/Namsan, pull requests merged in 2023-04, with the labels that each got.

#23 Feature/introduce mobile
  src/components/introduce/AnimationImage/AnimationImage.style.ts
  src/components/introduce/AnimationImage/AnimationImage.tsx
  src/components/introduce/IntroduceWrapper/IntroduceWrapper.style.ts
  src/components/introduce/IntroduceWrapper/IntroduceWrapper.tsx
  src/intl/ko.json
  src/styles/varialbes.style.ts
  yarn.lock
Labels: feat

#24 Feature/member single mobile
  src/components/member/IntroduceItem/IntroduceItem.style.ts
  src/components/member/IntroduceItem/IntroduceItem.tsx
  src/components/member/Member/Member.const.ts
  src/components/member/Member/Member.style.ts
  src/intl/ko.json
  src/styles/varialbes.style.ts
Labels: feat

#29 [FIX] 안쓰는 파일 제거
  src/components/common/Loading/Loading.tsx
Labels: fix

#22 Feature/work page
  src/api/work.api.ts
  src/components/work/DetailPage.tsx
  src/components/work/index.tsx
  src/components/work/work.styled.ts
  src/pages/work/[...].tsx
  src/pages/work/[id].tsx
  src/pages/work/index.tsx
Labels: fix

#26 약관 페이지 추가
  gatsby-config.ts
  package.json
  src/components/common/Footer/Footer.const.ts
  src/components/policy/Policy.style.ts
  src/content/policy/disclaimer.md
  src/content/policy/privacy.md
  src/pages/policy/{markdownRemark.frontmatter__slug}.tsx
  yarn.lock
Labels: fix, feat, chore

#36 소식 페이지 검색기능 + 페이지네이션(작업중)
  functions/src/index.ts
  gatsby-config.ts
  package.json
  src/api/algolia.ts
  src/api/index.api.ts
  src/api/news.api.ts
  src/assets/imgs/arrow_left_th10.svg
  src/assets/imgs/arrow_left_th10_strong.svg
  src/assets/imgs/arrow_right_th10.svg
  src/assets/imgs/arrow_right_th10_strong.svg
  src/components/news/Main/Main.style.ts
  src/components/news/Main/Main.tsx
  src/components/news/Main/main.interface.ts
  src/components/news/Pagination/Pagination.helper.ts
  src/components/news/Pagination/Pagination.style.ts
  src/components/news/Pagination/Pagination.tsx
  src/components/news/Pagination/index.ts
  src/pages/news.tsx
  src/styles/varialbes.style.ts
  yarn.lock
Labels: feat, style

#35 Fix/page/main
  .github/ pull_request_template.md
  src/api/main.api.ts
  src/assets/imgs/ic_m_menu_nor.svg
  src/assets/imgs/logo-mobile-gnb.svg
  src/components/common/Footer/Footer.const.ts
  src/components/common/GNB/GNB.interface.ts
  src/components/common/GNB/GNB.style.ts
  src/components/common/GNB/GNB.tsx
  src/components/common/Layout/Layout.interface.ts
  src/components/common/Layout/Layout.style.ts
  src/components/common/Layout/Layout.tsx
  src/components/icons/LogoIcon/LogoIcon.tsx
  src/components/icons/LogoIcon/index.ts
  src/components/icons/MenuIcon/MenuIcon.tsx
  src/components/main/Banner/Banner.style.ts
  src/components/main/Banner/Banner.tsx
  src/components/main/FifthSection/FifthSection.hook.ts
  src/components/main/FifthSection/FifthSection.style.ts
  src/components/main/FifthSection/FifthSection.tsx
  src/components/main/FirstSection/FirstSection.hook.ts
  src/components/main/FirstSection/FirstSection.interface.ts
  src/components/main/FirstSection/FirstSection.style.ts
  src/components/main/FirstSection/FirstSection.tsx
  src/components/main/ForthSection/ForthSection.hook.ts
  src/components/main/ForthSection/ForthSection.interface.ts
  src/components/main/ForthSection/ForthSection.style.ts
  src/components/main/ForthSection/ForthSection.tsx
  src/components/main/SecondSection/SecondSection.style.ts
  src/components/main/ThirdSection/ThirdSection.hook.ts
  src/components/main/ThirdSection/ThirdSection.style.ts
  src/components/main/ThirdSection/ThirdSection.tsx
  src/components/news/Card/Card.tsx
  src/hooks/useResize.ts
  src/intl/en.json
  src/intl/ko.json
  src/pages/index.tsx
  src/styles/varialbes.style.ts
Labels: fix

#42 페이지네이션 작업완료 + Card 컴포넌트 lazy loading
  src/components/news/Card/Card.interface.ts
  src/components/news/Card/Card.style.ts
  src/components/news/Card/Card.tsx
  src/components/news/Main/Main.style.ts
  src/components/news/Main/Main.tsx
  src/components/news/Main/useMain.hook.ts
  src/components/news/Pagination/Pagination.helper.ts
  src/components/news/Pagination/Pagination.interface.ts
  src/components/news/Pagination/Pagination.tsx
Labels: fix, style, refactor

#45 Fix/page/main
  src/components/common/GNB/GNB.style.ts
  src/components/common/GNB/GNB.tsx
  src/components/common/Layout/Layout.style.ts
  src/components/common/Layout/Layout.tsx
  src/components/main/Banner/Banner.style.ts
  src/components/main/FifthSection/FifthSection.style.ts
  src/components/main/FirstSection/FirstSection.hook.ts
  src/components/main/FirstSection/FirstSection.interface.ts
  src/components/main/FirstSection/FirstSection.style.ts
  src/components/main/ForthSection/ForthSection.style.ts
  src/components/main/ForthSection/ForthSection.tsx
  src/components/main/ThirdSection/ThirdSection.hook.ts
  src/components/main/ThirdSection/ThirdSection.style.ts
  src/hooks/useResize.ts
  src/intl/ko.json
  src/pages/index.tsx
Labels: fix, refactor

#47 [CHORE] 파이어베이스 호스팅 셋팅
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .gitignore
  firebase.json
Labels: chore
