Repository NAMSAN-MT/Namsan, pull requests merged in 2023-05, with the labels that each got.

#54 Layout > 멀티 플로팅 영역(+Toast 기능) 작업
  src/assets/imgs/ic_copy.svg
  src/components/common/BaseButton/BaseButton.helper.ts
  src/components/common/BaseButton/BaseButton.interface.ts
  src/components/common/BaseButton/BaseButton.style.ts
  src/components/common/GNB/GNB.interface.ts
  src/components/common/Layout/Layout.hook.ts
  src/components/common/Layout/Layout.style.ts
  src/components/common/Layout/Layout.tsx
  src/components/icons/NewsListIcon/NewsListIcon.tsx
  src/components/icons/NewsListIcon/index.ts
Labels: feat, style

#53 [FIX] 메인페이지
  src/components/main/ForthSection/ForthSection.style.ts
  src/components/main/ForthSection/ForthSection.tsx
  src/components/main/ThirdSection/ThirdSection.style.ts
  src/components/news/Card/Card.tsx
  src/components/news/Main/Main.tsx
  src/intl/en.json
Labels: fix

#46 [FIX] GNB filter 적용
  functions/src/index.ts
Labels: fix

#56 Feature/work page
  gatsby-node.ts
  src/api/work.api.ts
  src/components/work/DetailPage.tsx
  src/components/work/index.tsx
  src/components/work/work.interface.tsx
  src/intl/en.json
  src/intl/ko.json
  src/pages/work/[id].tsx
  src/pages/work/index.tsx
  yarn.lock
Labels: fix, feat

#59 메인 영역 뉴스 조회 오류 수정
  .env.development
  src/api/index.api.ts
  src/api/news.api.ts
  src/components/main/ForthSection/ForthSection.tsx
  src/components/news/Card/Card.interface.ts
  src/components/news/Card/Card.tsx
  src/components/news/Main/Main.hook.ts
  src/components/news/Main/Main.tsx
Labels: fix, refactor

#78 [FIX] 소식 상세 정보 CSR 호출 변경
  src/components/news/Main/Main.tsx
  src/components/news/NewsDetail/NewsDetail.tsx
  src/intl/ko.json
  src/pages/news/[id].tsx
Labels: fix

#84 Fix/main page
  gatsby-config.ts
  src/components/common/GNB/GNB.hook.ts
  src/components/common/GNB/GNB.style.ts
  src/components/common/GNB/GNB.tsx
Labels: fix

#86 뉴스 리스트 요약 조회
  functions/.eslintrc.js
  src/api/news.api.ts
  src/components/news/Card/Card.interface.ts
  src/components/news/Card/Card.tsx
  src/components/news/Main/Main.hook.ts
  src/interface/api.interface.ts
Labels: refactor

#88 소식 상세 페이지 조회 방식 변경 (feat. graphql)
  functions/src/index.ts
  gatsby-node.ts
  src/components/news/Card/Card.style.ts
  src/components/news/NewsDetail/NewsDetail.interface.ts
  src/components/news/NewsDetail/NewsDetail.style.ts
  src/components/news/NewsDetail/NewsDetail.tsx
  src/interface/api.interface.ts
  src/pages/news/[id].tsx
Labels: feat, style, refactor

#87 Fix/main page
  package.json
  src/assets/lottie/button_link.json
  src/assets/lottie/button_menu.json
  src/assets/lottie/button_top.json
  src/assets/lottie/focus.json
  src/assets/lottie/focus_move.json
  src/assets/lottie/navigation_down.json
  src/assets/lottie/navigation_up.json
  src/components/common/BaseButton/BaseButton.style.ts
  src/components/common/Footer/Footer.style.ts
  src/components/common/GNB/GNB.style.ts
  src/components/common/GNB/GNB.tsx
  src/components/common/Layout/Layout.hook.ts
  src/components/common/Layout/Layout.style.ts
  src/components/common/Layout/Layout.tsx
  src/components/common/Loading/Loading.tsx
  src/components/common/LottieWrapper/LottieWrapper.interface.ts
  src/components/common/LottieWrapper/LottieWrapper.tsx
  src/components/common/LottieWrapper/index.tsx
  src/components/main/Banner/Banner.style.ts
  src/components/main/FifthSection/FifthSection.style.ts
  src/components/main/FirstSection/FirstSection.hook.ts
  src/components/main/FirstSection/FirstSection.tsx
  src/components/main/ForthSection/ForthSection.style.ts
  src/components/main/ForthSection/ForthSection.tsx
  src/components/main/SecondSection/SecondSection.style.ts
  src/components/main/SecondSection/SecondSection.tsx
  src/components/main/ThirdSection/ThirdSection.hook.ts
  src/components/main/ThirdSection/ThirdSection.interface.ts
  src/components/main/ThirdSection/ThirdSection.style.ts
  src/components/main/ThirdSection/ThirdSection.tsx
  src/components/news/Card/Card.tsx
  src/index.d.ts
  src/pages/index.tsx
  yarn.lock
Labels: fix

#96 [Fix] MAIN
  src/assets/imgs/logo-mobile-gnb-white.svg
  src/assets/imgs/logo-mobile-gnb.svg
  src/components/common/GNB/GNB.style.ts
  src/components/common/GNB/GNB.tsx
  src/components/common/Layout/Layout.hook.ts
  src/components/common/Layout/Layout.interface.ts
  src/components/common/Layout/Layout.tsx
  src/components/icons/LogoIcon/LogoIcon.tsx
  src/components/members/SelectBox/SelectBox.tsx
  src/components/work/DetailPage.tsx
  src/components/work/work.styled.ts
Labels: fix, feat

#97 Feature/news design refactor
  src/assets/imgs/ic_search_m.svg
  src/components/common/Input/Input.interface.ts
  src/components/common/Input/Input.tsx
  src/components/common/Layout/Layout.interface.ts
  src/components/common/Layout/Layout.style.ts
  src/components/common/Layout/Layout.tsx
  src/components/icons/LineArrowIcon/LineArrowIcon.tsx
  src/components/icons/SearchIcon/SearchIcon.tsx
  src/components/members/SearchBar/SearchBar.style.ts
  src/components/news/Card/Card.interface.ts
  src/components/news/Card/Card.style.ts
  src/components/news/Card/Card.tsx
  src/components/news/Main/Main.hook.ts
  src/components/news/Main/Main.style.ts
  src/components/news/Main/Main.tsx
  src/components/news/NewsDetail/NewsDetail.style.ts
  src/components/news/NewsWrapper/NewsWrapper.style.ts
  src/components/news/Pagination/Pagination.style.ts
  src/pages/news.tsx
Labels: feat, style, refactor

#100 [FEAT] Develop
  src/assets/imgs/ic_search_m.svg
  src/assets/imgs/logo-mobile-gnb-white.svg
  src/assets/imgs/logo-mobile-gnb.svg
  src/components/common/GNB/GNB.style.ts
  src/components/common/GNB/GNB.tsx
  src/components/common/Input/Input.interface.ts
  src/components/common/Input/Input.tsx
  src/components/common/Layout/Layout.hook.ts
  src/components/common/Layout/Layout.interface.ts
  src/components/common/Layout/Layout.style.ts
  src/components/common/Layout/Layout.tsx
  src/components/icons/LineArrowIcon/LineArrowIcon.tsx
  src/components/icons/LogoIcon/LogoIcon.tsx
  src/components/icons/SearchIcon/SearchIcon.tsx
  src/components/members/SearchBar/SearchBar.style.ts
  src/components/members/SelectBox/SelectBox.tsx
  src/components/news/Card/Card.interface.ts
  src/components/news/Card/Card.style.ts
  src/components/news/Card/Card.tsx
  src/components/news/Main/Main.hook.ts
  src/components/news/Main/Main.style.ts
  src/components/news/Main/Main.tsx
  src/components/news/NewsDetail/NewsDetail.style.ts
  src/components/news/NewsWrapper/NewsWrapper.style.ts
  src/components/news/Pagination/Pagination.style.ts
  src/components/work/DetailPage.tsx
  src/components/work/work.styled.ts
  src/pages/news.tsx
Labels: fix, feat, refactor

#109 Feature/work page
  src/components/common/Container/Container.tsx
  src/components/common/List/List.style.ts
  src/components/member/Member/Member.tsx
  src/components/work/DetailPage.tsx
  src/components/work/work.styled.ts
Labels: style

#122 [FIX] 디자인 검수 + 메인 인트로 수정
  package.json
  src/components/common/GNB/GNB.style.ts
  src/components/main/Banner/Banner.style.ts
  src/components/main/FifthSection/FifthSection.style.ts
  src/components/main/FirstSection/FirstSection.hook.ts
  src/components/main/FirstSection/FirstSection.style.ts
  src/components/main/FirstSection/FirstSection.tsx
  src/components/main/ForthSection/ForthSection.style.ts
  src/components/main/ThirdSection/ThirdSection.style.ts
  src/styles/GlobalStyles.ts
  yarn.lock
Labels: fix, feat, chore

#127 소식 상세 아이콘 이슈 수정
  src/components/news/NewsDetail/NewsDetail.style.ts
  src/components/news/NewsDetail/NewsDetail.tsx
  src/intl/en.json
Labels: style

#143 [FIX] 20230530 디자인 검수 수정
  src/components/common/Footer/Footer.style.ts
  src/components/common/GNB/GNB.style.ts
  src/components/common/GNB/GNB.tsx
  src/components/icons/LogoIcon/LogoIcon.tsx
  src/components/main/Banner/Banner.style.ts
  src/components/main/FifthSection/FifthSection.style.ts
  src/components/main/FirstSection/FirstSection.style.ts
  src/components/main/ForthSection/ForthSection.style.ts
  src/components/main/ThirdSection/ThirdSection.style.ts
Labels: fix

#144 [FIX] 20230530 디자인 검수 수정
  src/components/common/Footer/Footer.style.ts
  src/components/common/GNB/GNB.style.ts
  src/components/common/GNB/GNB.tsx
  src/components/icons/LogoIcon/LogoIcon.tsx
  src/components/main/Banner/Banner.style.ts
  src/components/main/FifthSection/FifthSection.style.ts
  src/components/main/FirstSection/FirstSection.style.ts
  src/components/main/ForthSection/ForthSection.style.ts
  src/components/main/ThirdSection/ThirdSection.style.ts
Labels: fix

#156 [FIX] 검수 수정
  src/components/common/GNB/GNB.style.ts
  src/components/common/GNB/GNB.tsx
  src/components/common/Layout/Layout.hook.ts
  src/components/common/Layout/Layout.interface.ts
  src/components/common/Layout/Layout.tsx
  src/components/common/LottieWrapper/LottieWrapper.interface.ts
  src/components/common/LottieWrapper/LottieWrapper.tsx
  src/components/main/FirstSection/FirstSection.style.ts
Labels: fix
