Repository NAMSAN-MT/Namsan, pull requests merged in 2023-03, with the labels that each got.

#9 feat: feature/gnb
  package.json
  src/assets/imgs/ic_+_hover.svg
  src/assets/imgs/ic_+_nor.svg
  src/assets/imgs/ic_-_hover.svg
  src/assets/imgs/ic_-_nor.svg
  src/assets/imgs/ic_arrow_down_th10.svg
  src/assets/imgs/ic_arrow_down_th15.svg
  src/assets/imgs/ic_arrow_drop_down.svg
  src/assets/imgs/ic_arrow_drop_left.svg
  src/assets/imgs/ic_arrow_drop_right.svg
  src/assets/imgs/ic_arrow_drop_up.svg
  src/assets/imgs/ic_arrow_left_th10.svg
  src/assets/imgs/ic_arrow_left_th15.svg
  src/assets/imgs/ic_arrow_left_th5.svg
  src/assets/imgs/ic_arrow_right_th10.svg
  src/assets/imgs/ic_arrow_right_th15.svg
  src/assets/imgs/ic_arrow_right_th5.svg
  src/assets/imgs/ic_arrow_up_th10.svg
  src/assets/imgs/ic_arrow_up_th15.svg
  src/assets/imgs/ic_home.svg
  src/assets/imgs/ic_menu_nor.svg
  src/assets/imgs/ic_open.svg
  src/components/common/BaseButton/BaseButton.style.ts
  src/components/common/GNB/GNB.const.ts
  src/components/common/GNB/GNB.hook.ts
  src/components/common/GNB/GNB.style.ts
  src/components/common/GNB/GNB.tsx
  src/components/common/GNB/index.tsx
  src/components/icons/AddIcon/AddIcon.tsx
  src/components/icons/AddIcon/index.ts
  src/components/icons/FilledArrowIcon/FilledArrowIcon.tsx
  src/components/icons/FilledArrowIcon/index.ts
  src/components/icons/HomeIcon/HomeIcon.tsx
  src/components/icons/HomeIcon/index.ts
  src/components/icons/IconWrapper/IconWrapper.style.tsx
  src/components/icons/IconWrapper/IconWrapper.tsx
  src/components/icons/IconWrapper/index.ts
  src/components/icons/LineArrowIcon/LineArrowIcon.tsx
  src/components/icons/LineArrowIcon/index.ts
  src/components/icons/MenuIcon/MenuIcon.tsx
  src/components/icons/MenuIcon/index.ts
  src/components/icons/RemoveIcon/RemoveIcon.tsx
  src/components/icons/RemoveIcon/index.ts
  src/index.d.ts
  src/pages/index.tsx
  src/styles/GlobalStyles.ts
  yarn.lock
Labels: feat

#7 GlobalStyle 피드백 반영 외.
  src/styles/mixin.style.ts
  src/styles/varialbes.style.ts
  yarn.lock
Labels: style, chore

#8 [feat]: 다국어 기능 추가 (gatsby plugin intl)
  gatsby-config.ts
  package.json
  src/intl/en.json
  src/intl/ko.json
  src/pages/test.tsx
  yarn.lock
Labels: feat

#20 [FEAT] 메인페이지
  gatsby-config.ts
  package.json
  src/api/firebase.ts
  src/api/index.api.ts
  src/api/main.api.ts
  src/components/common/AnimationWrapper/AnimationWrapper.helper.ts
  src/components/common/AnimationWrapper/AnimationWrapper.interface.ts
  src/components/common/AnimationWrapper/AnimationWrapper.tsx
  src/components/common/AnimationWrapper/index.tsx
  src/components/common/GNB/GNB.tsx
  src/components/common/Layout/Layout.hook.ts
  src/components/common/Skeleton/Skeleton.interface.ts
  src/components/common/Skeleton/Skeleton.style.ts
  src/components/common/Skeleton/Skeleton.tsx
  src/components/common/Skeleton/index.tsx
  src/components/main/FifthSection/FifthSection.hook.ts
  src/components/main/FifthSection/FifthSection.tsx
  src/components/main/FirstSection/FirstSection.hook.ts
  src/components/main/FirstSection/FirstSection.style.ts
  src/components/main/FirstSection/FirstSection.tsx
  src/components/main/ForthSection/ForthSection.hook.ts
  src/components/main/ForthSection/ForthSection.tsx
  src/components/main/SecondSection/SecondSection.hook.ts
  src/components/main/SecondSection/SecondSection.tsx
  src/components/main/ThirdSection/ThirdSection.hook.ts
  src/components/main/ThirdSection/ThirdSection.tsx
  src/hooks/useDateFns.ts
  src/pages/index.tsx
  src/pages/member.tsx
  tsconfig.json
  yarn.lock
Labels: fix, feat, refactor

#18 [FEAT]: 단일 구성원 페이지
  package.json
  src/api/member.api.ts
  src/assets/imgs/member_bg.jpg
  src/components/common/Divider/Divider.style.ts
  src/components/common/Divider/Divider.tsx
  src/components/common/Divider/index.tsx
  src/components/contact/ContactSection/ContactSection.style.ts
  src/components/contact/ContactWrapper/ContactWrapper.interface.ts
  src/components/contact/ContactWrapper/ContactWrapper.style.ts
  src/components/contact/ContactWrapper/ContactWrapper.tsx
  src/components/contact/ContactWrapper/index.tsx
  src/components/contact/RecruiteSection/RecruiteSection.style.ts
  src/components/member/IntroduceItem/IntroduceItem.interface.ts
  src/components/member/IntroduceItem/IntroduceItem.style.ts
  src/components/member/IntroduceItem/IntroduceItem.tsx
  src/components/member/IntroduceItem/IntroduceItem.type.ts
  src/components/member/IntroduceItem/index.tsx
  src/components/member/Member/Member.const.ts
  src/components/member/Member/Member.interface.ts
  src/components/member/Member/Member.style.ts
  src/components/member/Member/Member.tsx
  src/components/member/Member/index.tsx
  src/components/members/MemberItem/MemberItem.interface.ts
  src/components/members/MemberItem/MemberItem.tsx
  src/components/members/MemberList/MemberList.tsx
  src/components/members/MembersWrapper/MembersWarpper.helper.ts
  src/custom.d.ts
  src/interface/api.interface.ts
  src/intl/ko.json
  src/pages/contact.tsx
  src/pages/member/[id].tsx
  src/styles/GlobalStyles.ts
  src/type/api.type.ts
Labels: feat

#21 [fix]: SSR 오류 수정
  src/components/common/GNB/GNB.style.ts
  src/components/common/GNB/GNB.tsx
  src/components/common/Input/Input.interface.ts
  src/components/main/FifthSection/FifthSection.tsx
  src/components/main/ThirdSection/ThirdSection.tsx
  src/pages/index.tsx
Labels: fix
