Repository NAMSAN-MT/Namsan, pull requests merged in 2023-06, with the labels that each got.

#171 [FIX] 20230603 디자인 검수 적용
  src/components/common/Input/Input.style.ts
  src/components/contact/ContactSection/ContactSection.tsx
  src/components/contact/RecruiteSection/RecruiteSection.tsx
  src/components/work/DetailPage.tsx
  src/components/work/work.styled.ts
  src/content/policy/privacy.md
  src/intl/ko.json
Labels: fix

#172 [FIX] 20230602 디자인 검수 수정 반영
  src/components/common/Input/Input.style.ts
  src/components/contact/ContactSection/ContactSection.tsx
  src/components/contact/RecruiteSection/RecruiteSection.tsx
  src/components/work/DetailPage.tsx
  src/components/work/work.styled.ts
  src/content/policy/privacy.md
  src/intl/ko.json
Labels: fix

#175 [FIX] 업무분야 디자인 수정 반영
  src/components/member/Member/Member.tsx
  src/components/work/work.styled.ts
Labels: fix

#177 [FIX] 메인 20230605 디자인 반영 수정
  src/components/main/Banner/Banner.style.ts
Labels: fix

#178 [FIX] 메인 20230605 디자인 반영 수정
  src/components/main/Banner/Banner.style.ts
Labels: fix

#191 [FIX] 스타일 및 버그 수정(회사소개서, 인재모집)
  src/components/main/Banner/Banner.tsx
  src/components/main/FifthSection/FifthSection.hook.ts
Labels: fix

#212 [FIX] 영문 스타일 및 기능 작업
  src/assets/imgs/ic_download.svg
  src/components/common/BaseButton/BaseButton.style.ts
  src/components/common/GNB/GNB.hook.ts
  src/components/common/GNB/GNB.style.ts
  src/components/common/GNB/GNB.tsx
  src/components/main/FirstSection/FirstSection.style.ts
  src/components/news/Main/Main.tsx
  src/components/news/NewsWrapper/NewsWrapper.tsx
  src/content/policy/privacy.md
  src/intl/en.json
  src/intl/ko.json
  src/pages/news.tsx
Labels: fix

#215 [FIX] meta tag
  gatsby-config.ts
Labels: fix

#216 [FIX] 영문 스타일 및 기능 작업
  gatsby-config.ts
  src/assets/imgs/ic_download.svg
  src/components/common/BaseButton/BaseButton.style.ts
  src/components/common/Container/Container.tsx
  src/components/common/GNB/GNB.hook.ts
  src/components/common/GNB/GNB.style.ts
  src/components/common/GNB/GNB.tsx
  src/components/common/List/List.style.ts
  src/components/contact/ContactSection/ContactSection.tsx
  src/components/contact/RecruiteSection/RecruiteSection.style.ts
  src/components/introduce/AnimationImage/AnimationImage.style.ts
  src/components/introduce/IntroduceWrapper/IntroduceWrapper.style.ts
  src/components/introduce/IntroduceWrapper/IntroduceWrapper.tsx
  src/components/main/FirstSection/FirstSection.style.ts
  src/components/member/Member/Member.tsx
  src/components/members/MemberItem/MemberItem.style.ts
  src/components/members/MemberItem/MemberItem.tsx
  src/components/members/MemberList/MemberList.style.ts
  src/components/members/MemberList/MemberList.tsx
  src/components/members/SearchBar/SearchBar.tsx
  src/components/news/Main/Main.tsx
  src/components/news/NewsWrapper/NewsWrapper.tsx
  src/components/work/DetailPage.tsx
  src/components/work/work.styled.ts
  src/content/policy/privacy.md
  src/intl/en.json
  src/intl/ko.json
  src/pages/news.tsx
Labels: fix, feat

#219 [FIX] 폰트 수정, manifest 수정
  gatsby-config.ts
  src/components/main/FirstSection/FirstSection.style.ts
Labels: fix

#221 [FIX] 개인정보처리 방침 수정
  src/components/main/FirstSection/FirstSection.style.ts
  src/components/main/ThirdSection/ThirdSection.style.ts
  src/content/policy/privacy.md
Labels: fix

#227 날짜 포멧 수정
  src/api/news.api.ts
  src/components/news/NewsDetail/NewsDetail.helper.ts
  src/components/news/NewsDetail/NewsDetail.tsx
Labels: feat

#229 [FEAT] 파비콘 수정
  gatsby-config.ts
  package.json
  src/components/common/Seo/Seo.tsx
  static/favicon.ico
  yarn.lock
Labels: fix

#230 [FEAT] 파비콘 수정
  gatsby-config.ts
  package.json
  src/components/common/Seo/Seo.tsx
  static/favicon.ico
  yarn.lock
Labels: fix

#231 [FIX] 메인 폰트 수정 & 업무분야 사이즈 수정
  src/components/main/FirstSection/FirstSection.style.ts
  src/components/main/ThirdSection/ThirdSection.style.ts
Labels: fix
